server:
  port: 8001
spring:
  application:
    name: UserProvider
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
      
ProviderVersion: UserProvider01