server:
  port: 9003
spring:
  application:
    name: UserWeb03
  thymeleaf:
    cache: false
userprovider:
  ribbon:
    #配置指定服务的负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #是否对所有操作都进行重试
    OkToRetryOnAllOperations: true
    #切换实例的重试次数
    MaxAutoRetriesNextServer: 1
    #对当前实例的重试次数
    MaxAutoRetries: 1